# The name and the category can be different.  The name is optional
parameters:
    cemeteries:
        'Binnaway General Cemetery':
            category: 'Binnaway General Cemetery, Binnaway, New South Wales'
            name: 'Binnaway Cemetery, Binnaway, New South Wales'
        'Bong Bong Anglican Cemetery':
            category: 'Bong Bong Church Cemetery, Moss Vale, New South Wales'
            name: 'Bong Bong Anglican Cemetery, Moss Vale, New South Wales'
        'Bong Bong Presbyterian Cemetery':
            category: 'Bong Bong Church Cemetery, Moss Vale, New South Wales'
            name: 'Bong Bong Presbyterian Cemetery, Moss Vale, New South Wales'
