parameters:
    name_type_list:
        - aka
        - birth
        - immigration
        - maiden
        - married
    do_the_sort: false
    joiners:
        passed_away:
            at: at
            late of: late of
            registered at: registered at
            at the: at the
            in the: in the
        marriage:
            at: at
            in the: in the
            registered at: registered at
    loader:
        group_size_min: 6
        group_size_max: 13
        group_pause_min: 10000  // times are in milliseconds
        group_pause_max: 35000
        profile_pause_min: 2500
        profile_pause_max: 7500
