parameters:
    name_type_list:
        - aka
        - birth
        - immigration
        - maiden
        - married
    cemeteries:
        'Appin Catholic Cemetery St Bede':
            category: 'St Bede''s Catholic Cemetery, Appin, New South Wales'
        'Bathurst Cemetery':
            category: 'Bathurst Cemetery, Bathurst, New South Wales'
        'Bega Cemetery':
            category: 'Bega Cemetery, Bega, New South Wales'
        'Binnaway General Cemetery':
            category: 'Binnaway General Cemetery, Binnaway, New South Wales'
        'Bong Bong Anglican Cemetery':
            category: 'Bong Bong Church Cemetery, Moss Vale, New South Wales'
            name: Bong Bong Anglican Cemetery, Moss Vale, New South Wales
        'Bong Bong Presbyterian Cemetery':
            category: 'Bong Bong Church Cemetery, Moss Vale, New South Wales'
            name: Bong Bong Presbyterian Cemetery, Moss Vale, New South Wales
        'Brisbane South Cemetery':
            category: 'South Brisbane Cemetery, Dutton Park, Queensland'
        'Bungendore Cemetery':
            category: 'Bungendore Cemetery, Bungendore, New South Wales'
        'Coolah Cemetery':
            category: 'Coolah Cemetery, Coolah, New South Wales'
        'Coonabarabran Anglican Cemetery':
            category: 'Coonabarabran Anglican Cemetery, Coonabarabran, New South Wales'
        'Cudgegong Cemetery':
            category: 'Cudgegong General Cemetery, Cudgegong, New South Wales'
        'Delungra Cemetery':
            category: 'Delungra Cemetery, Delungra, New South Wales'
        'Dunedoo Cemetery':
            category: 'Dunedoo Cemetery, Dunedoo, New South Wales'
        'Eastern Suburbs Memorial Park':
            category: 'Eastern Suburbs Memorial Park, Matraville, New South Wales'
        'Forbes Cemetery':
            category: 'Forbes Cemetery, Forbes, New South Wales'
        'Forest Lawn Memorial Park, Leppington':
            category: 'Forest Lawn Memorial Park, Leppington, New South Wales'
        'Gulgong General Cemetery':
            category: 'Gulgong General Cemetery, Gulgong, New South Wales'
        'Innes Gardens Memorial Park, Port Macquarie':
            category: 'Innes Gardens Memorial Park, Port Macquarie, New South Wales'
        'Jilliby Cemetery':
            category: 'Jilliby Cemetery, Jilliby, New South Wales'
        'Killarney Cemetery':
            category: 'Killarney Cemetery, Killarney, Queensland'
        'Killarney Lawn Cemetery':
            category: 'Killarney Cemetery, Killarney, Queensland'
        'Laurieton Cemetery':
            category: 'Laurieton Cemetery, Laurieton, New South Wales'
        'Macquarie Park Cemetery and Crematorium':
            category: 'Macquarie Park Cemetery and Crematorium, North Ryde, New South Wales'
        'Mendooran Cemetery':
            category: 'Mendooran Cemetery, Mendooran, New South Wales'
        'Mudgee General Cemetery':
            category: 'Mudgee General Cemetery, Mudgee, New South Wales'
        'Mudgee Lawn Cemetery':
            category: 'Mudgee Lawn Cemetery, Buckaroo, New South Wales'
        'Myall Remembrance Park':
            category: 'Myall Remembrance Park, Dalby, Queensland'
        'Noraville Cemetery':
            category: 'Noraville Cemetery, Wyong, New South Wales'
        'Parkes Cemetery':
            category: 'Parkes General Cemetery, Parkes, New South Wales'
        'Picton General Cemetery':
            category: 'Picton General Cemetery, Picton, New South Wales'
        'Pinnaroo Lawn Cemetery, Queensland':
            category: 'Pinnaroo Lawn Cemetery, Bridgeman Downs, Queensland'
        'Port Macquarie General Cemetery':
            category: 'Port Macquarie General Cemetery, Port Macquarie, New South Wales'
        'Portland Cemetery':
            category: 'Portland General Cemetery, Portland, New South Wales'
        'Queanbeyan Lawn Cemetery':
            category: 'Queanbeyan Lawn Cemetery and Memorial Gardens, Jerrabomberra, New South Wales'
        'Rookwood Anglican Cemetery':
            category: 'Rookwood Anglican Cemetery, Rookwood, New South Wales'
        'Rookwood General Cemetery':
            category: 'Rookwood General Cemetery, Rookwood, New South Wales'
        'Rookwood Memorial Gardens and Crematorium':
            category: 'Rookwood Memorial Gardens and Crematorium, Rookwood, New South Wales'
        'Windeyer Catholic Cemetery':
            category: 'Windeyer Catholic Cemetery, Windeyer, New South Wales'
        'Sandgate Cemetery':
            category: 'Sandgate Cemetery, Sandgate, New South Wales'
        'Scarborough Wombarra Cemetery':
            category: 'Scarborough Wombarra Cemetery, Wombarra, New South Wales'
        'Springwood Cemetery':
            category: 'Springwood Cemetery, Springwood, New South Wales'
        'St Marys Cemetery':
            category: 'St Marys General Cemetery, St Marys, New South Wales'
        'Warialda General Cemetery':
            category: 'Warialda General Cemetery, Warialda, New South Wales'
        'Windsor, St Matthew Anglican Cemetery':
            category: 'St Matthew''s Anglican Cemetery, Windsor, New South Wales'
        'Woden Cemetery, Phillip, ACT':
            category: 'Woden Cemetery, Phillip, Australian Capital Territory'
        'Wollongong Memorial Gardens':
            category: 'Wollongong Memorial Gardens, Unanderra, New South Wales'
        'Woronora Memorial Park':
            category: 'Woronora Memorial Park, Sutherland, New South Wales'
        'Orange Cemetery':
            category: 'Orange Cemetery, Orange, New South Wales'
        'Palmdale Cemetery':
            category: 'Palmdale Lawn Cemetery and Memorial Park, Palmdale, New South Wales'
        'Menindee Cemetery':
            category: 'Menindee Cemetery, Menindee, New South Wales'
        'Macquarie Park Cemetery':
            category: 'Macquarie Park Cemetery and Crematorium, North Ryde, New South Wales'
        'Tweed Heads Old Cemetery':
            category: 'Tweed Heads Old General Cemetery, Tweed Heads, New South Wales'
        'Prospect Cemetery St Bartholomew':
            category: 'St Bartholomew''s Anglican Cemetery, Prospect, New South Wales'
        'Northern Suburbs Crematorium':
            category: 'Northern Suburbs Memorial Gardens and Crematorium, North Ryde, New South Wales'
        'Enfield Anglican Cemetery St Thomas':
            category: 'St Thomas'' Anglican Cemetery, Enfield, New South Wales'
    congregations:
        'Mascot Catholic St Therese':
            name: 'St Therese''s Catholic Church'
            category: 'St Therese''s Catholic Church, Rosebery, New South Wales'
        'Tallawang Catholic St Joseph':
            name: 'St Joseph''s Catholic Church'
            category: 'St Joseph''s Catholic Church, Tallawang, New South Wales'
        'Bathurst Methodist Church':
            name: 'Bathurst Methodist Church'
            category: 'Bathurst Uniting Church, Bathurst, New South Wales'
        'Neutral Bay Catholic St Joseph':
            name: 'St Joseph''s Catholic Church'
            category: 'St Joseph''s Catholic Church, Neutral Bay, New South Wales'
        'Strathfield Catholic St Martha':
            name: 'St Martha''s Catholic Church'
            category: 'St Martha''s Catholic Church, Strathfield, New South Wales'
        'Rylstone St Malachy Catholic Church':
            name: 'St Malachy''s Catholic Church'
            category: 'St Malarchy''s Catholic Church, Rylstone, New South Wales'
        'Rylstone Methodist Church':
            name: 'Rylstone Mthodist Church'
            category: 'Rylstone Uniting Church, Rylstone, New South Wales'
        'Marrickville Church of England St Clement':
            name: 'St Clement''s Church of England'
            category: 'St Clement''s Anglican Church, Marrickville, New South Wales'
        'Inverell Church of England, St Augustine':
            name: 'St Augustine''s Church of England'
            category: 'St Augustine''s Anglican Church, Inverell, New South Wales'
        'Inverell Anglican, St Augustine':
            name: 'St Augustine''s Anglican Church'
            category: 'St Augustine''s Anglican Church, Inverell, New South Wales'
        'Inverell Presbyterian':
            name: 'Inverell Presbyterian Church'
            category: 'Inverell Presbyterian Church, Inverell, New South Wales'
        'Inverell Catholic Sacred Heart':
            name: 'Sacred Heart Catholic Church'
            category: 'Sacred Heart Catholic Church, Inverell, New South Wales'
        'Delungra Presbyterian St Stephen':
            name: 'St Stephen''s Presbyterian Church'
            category: 'St Stephen''s Presbyterian Church, Delungra, New South Wales'
        'Mullamuddy Union':
            name: 'Mullamuddy Union Church'
            category: 'Union Church, Mullamuddy, New South Wales'
        'Binnaway Union':
            name: 'Binnaway Union Church'
            category: 'Binnaway Union Church, Binnaway, New South Wales'
        'Campsie Methodist':
            name: 'Campsie Methodist Church'
            category: 'Campsie Uniting Church, Campsie, New South Wales'
        'Campsie Uniting':
            name: 'Campsie Uniting Church'
            category: 'Campsie Uniting Church, Campsie, New South Wales'
        'Granville Anglican St Mark':
            name: 'St Mark''s Anglican Church'
            category: 'St Mark''s Anglican Church, Granville, New South Wales'
        'Granville Church of England St Mark':
            name: 'St Mark''s Church of Engalnd'
            category: 'St Mark''s Anglican Church, Granville, New South Wales'
        'Mudgee Anglican St John':
            name: 'St John the Baptist Anglican, Mudgee'
            category: 'St John the Baptist Anglican Church, Mudgee, New South Wales'
        'Mudgee Church of England St John':
            name: 'St John the Baptist Church of England, Mudgee'
            category: 'St John the Baptist Anglican Church, Mudgee, New South Wales'
        'Mudgee Catholic St Mary':
            name: 'St Mary''s Catholic Church, Mudgee'
            category: 'St Mary''s Catholic Church, Mudgee, New South Wales'
        'Mudgee Methodist Church':
            name: 'Mudgee Methodist Church'
            category: 'Mudgee Uniting Church, Mudgee, New South Wales'
        'Mudgee Presbyterian':
            name: 'St Paul''s Presbyterian Church'
            category: 'St Paul''s Presbyterian Church, Mudgee, New South Wales'
        'Toronto Methodist':
            name: 'Toronto Methodist Church'
            category: 'Toronto Uniting Church, Toronto, New South Wales'
        'Toronto Uniting':
            name: 'Toronto Uniting Church'
            category: 'Toronto Uniting Church, Toronto, New South Wales'
        'Wagga Wagga Anglican St John':
            name: 'St John''s Evangelist Anglican, Wagga Wagga'
            category: 'St John''s Evangelist Anglican Church, Wagga Wagga, New South Wales'
        'Wagga Wagga Church of England St John':
            name: 'St John''s Evangelist Church of England, Wagga Wagga'
            category: 'St John''s Evangelist Anglican Church, Wagga Wagga, New South Wales'
        'Goolma Church of England St Mark':
            name: 'St Mark''s Church of England'
            category: 'St Mark''s Anglican Church, Goolma, New South Wales'
        'Goolma Anglican St Mark':
            name: 'St Mark''s Anglican Church'
            category: 'St Mark''s Anglican Church, Goolma, New South Wales'
        'Wellington Anglican St John':
            name: 'St John the Baptist Anglican, Wellington'
            category: 'St John the Baptist Anglican Church, Wellington, New South Wales'
        'Wellington Church of England St John':
            name: 'St John the Baptist Church of England, Wellington'
            category: 'St John the Baptist Anglican Church, Wellington, New South Wales'
        'Manly Presbyterian St Andrew':
            name: 'St Andrew''s Presbyterian Church'
            category: 'St Andrew''s Presbyterian Church, Manly, New South Wales'
        'Sydney Church of England St James':
            name: 'St James'' Church of England'
            category: 'St James'' Anglican Church, Sydney, New South Wales'
        'Sydney Church of England St Phillip':
            name: 'St Phillip''s Church of England'
            category: 'St Philip''s Anglican Church, Sydney, New South Wales'
        'Sydney Catholic St Patrick':
            name: 'St Patrick''s Catholic Church'
            category: 'St Patrick''s Catholic Church, Sydney, New South Wales'
        'Sydney Anglican St James':
            name: 'St James'' Anglican Church'
            category: 'St James'' Anglican Church, Sydney, New South Wales'
        'Bathurst Anglican St Barnabas':
            name: 'St Barnabas'' Anglican Church'
            category: 'St Barnabas'' Anglican Church, Bathurst, New South Wales'
        'Bathurst Church of England St Barnabas':
            name: 'St Barnabas'' Church of England'
            category: 'St Barnabas'' Anglican Church, Bathurst, New South Wales'
        'Sydney Presbyterian St Stephen':
            name: 'St Stephen''s Presbyterian Church'
            category: 'St Stephen''s Uniting Church, Sydney, New South Wales'
        'Redfern Congregational Church':
            name: 'Redfern Congregational Church'
            category: 'Waterloo Congregational Church, Waterloo, New South Wales'
        'Penshurst Catholic St Declan':
            name: 'St Declan''s Catholic Church'
            category: 'St Declan''s Catholic Church, Penshurst, New South Wales'
        'Gulgong Church of England St Luke':
            name: 'St Luke''s Church of England'
            category: 'St Luke''s Anglican Church, Gulgong, New South Wales"'
        'Hurlstone Park Baptist':
            name: 'Hurlstone Park Baptist Church'
            category: 'Hurlstone Park Baptist Church, Hurlstone Park, New South Wales'
        'Bellevue Hill Church of England St Stephen':
            name: 'St Stephen''s Church of England'
            category: 'St Stephen''s Anglican Church, Bellevue Hill, New South Wales'
        'Limestone Flat Methodist Wesleyan':
            category: 'Wesleyan Chapel, Limestone Flat, New South Wales'
            name: 'Limestone Flat Methodist Church'
        'Windeyer Catholic St Killian':
            category: 'St Killian''s Catholic Church, Windeyer, New South Wales'
            name: 'St Killian''s Catholic Church'
        'Darlinghurst Catholic Sacred Heart':
            name: 'Sacred Heart Catholic Church'
            category: 'Sacred Heart Catholic Church, Darlinghurst, New South Wales'
        'Wellington Catholic St Patrick':
            name: 'St Patrick''s Catholic Church'
            category: 'St Patrick''s Catholic Church, Wellington, New South Wales'
        'Ryde Church of England':
            category: 'St Anne''s Anglican Church, Ryde, New South Wales'
            name: 'St Anne''s Church of England'
        'North Parramatta Church of Engand All Saints':
            category: 'All Saints Anglican Church, North Parramatta, New South Wales'
            name: 'All Saints Church of England'
        'Parramatta Church of Engand All Saints':
            category: 'All Saints Anglican Church, North Parramatta, New South Wales'
            name: 'All Saints Church of England'
        'Footscray Church of England St John':
            category: 'St John''s Anglican Church, Footscray, Victoria'
            name: 'St John''s Church of England'
        'Parramatta Church of England St John':
            category: 'St John''s Anglican Cathedral, Parramatta, New South Wales'
            name: 'St John''s Church of England Cathedral'
        'Chatswood Church of England, St Barnabas':
            category: 'St Barnabas'' Anglican Church, Roseville, New South Wales'
            name: 'St Barnabas'' Church of England'
        Millthorpe Church of England St Mark: 
            category: St Mark the Evangelist Anglican Church, Millthorpe, New South Wales
            name: St Mark the Evangelist Church of England
    locations:
        - 'Queen''s Pinch, New South Wales'
        - 'Bathurst, New South Wales'
        - 'Bedgerabong, New South Wales'
        - 'Belmont, New South Wales'
        - 'Bowraville, New South Wales'
        - 'Campsie, New South Wales'
        - 'Chester Hill, New South Wales'
        - 'Coffs Harbour, New South Wales'
        - 'Cudgegong, New South Wales'
        - 'Currumbin, Queensland'
        - 'Dural, New South Wales'
        - 'Eastwood, New South Wales'
        - Enfield, New South Wales
        - 'Engadine, New South Wales'
        - 'Erina, New South Wales'
        - 'Ermington, New South Wales'
        - 'Eurunderee, New South Wales'
        - 'Footscray, Victoria'
        - 'Granville, New South Wales'
        - 'Guildford, New South Wales'
        - 'Gulgamree, New South Wales'
        - 'Hunters Hill, New South Wales'
        - Limekilns, New South Wales
        - 'Limestone Flat, New South Wales'
        - 'Lithgow, New South Wales'
        - 'Menah, New South Wales'
        - 'Menindee, New South Wales'
        - 'Meroo, New South Wales'
        - Millthorpe, New South Wales
        - 'Mudgee, New South Wales'
        - 'Mullamuddy, New South Wales'
        - 'Northmead, New South Wales'
        - 'Northwood, New South Wales'
        - 'Northwood, New South Wales'
        - 'Orange, New South Wales'
        - 'Parramatta, New South Wales'
        - South Strathfield, New South Wales
        - 'Rooty Hill, New South Wales'
        - 'Roseville, New South Wales'
        - 'Rydalmere, New South Wales'
        - 'St Leonards, New South Wales'
        - 'Taree, New South Wales'
        - 'Wagga Wagga, New South Wales'
        - 'Wamberal, New South Wales'
        - 'Wellington, New South Wales'
        - 'West Ryde, New South Wales'
        - 'Windeyer, New South Wales'
