parameters:
    name_type_list:
        - aka
        - birth
        - immigration
        - maiden
        - married
    do_the_sort: false
    joiners:
        passed_away:
            at: at
            late of: late of
            registered at: registered at
            at the: at the
            in the: in the
        marriage:
            at: at
            in the: in the
            registered at: registered at
    loader:
        group_size_min: 9
        group_size_max: 17
        group_pause_min: 5000
        group_pause_max: 30000
        profile_pause_min: 3500
        profile_pause_max: 5500
        swap: "Frenchs Forest Bushland Cemetery, Davidson, New South Wales"
    max_daily_count: 1000
