parameters:
    name_type_list:
        - aka
        - birth
        - immigration
        - maiden
        - married
    do_the_sort: false
    joiners:
        passed_away:
            in: in
            at: at
            late of: late of