parameters:
    locations:
        - 'Annandale, New South Wales'
        - 'Ardlethan, New South Wales'
        - 'Balmain, New South Wales'
        - 'Bankstown, New South Wales'
        - 'Barraba, New South Wales'
        - 'Bathurst, New South Wales'
        - 'Bedgerabong, New South Wales'
        - 'Belmont, New South Wales'
        - 'Berrigan, New South Wales'
        - 'Bocoble, New South Wales'
        - 'Bowraville, New South Wales'
        - 'Broadmeadow, New South Wales'
        - 'Burwood Heights, New South Wales'
        - 'Burwood, New South Wales'
        - 'Campsie, New South Wales'
        - 'Canberra, Australian Capital Territory'
        - 'Chatswood, New South Wales'
        - 'Cherrybrook, New South Wales'
        - 'Chester Hill, New South Wales'
        - 'Clandulla, New South Wales'
        - 'Coffs Harbour, New South Wales'
        - 'Coffs Harbour, New South Wales'
        - 'Corrimal, New South Wales'
        - 'Cremorne, New South Wales'
        - 'Crudine, New South Wales'
        - 'Cudgegong, New South Wales'
        - 'Currumbin, Queensland'
        - 'Dartbrook, New South Wales'
        - 'Davistown, New South Wales'
        - 'Dural, New South Wales'
        - 'East Doncaster, Victoria'
        - 'Eastwood, New South Wales'
        - 'Ebenezer, New South Wales'
        - 'Echuca, Victoria'
        - 'Enfield, New South Wales'
        - 'Engadine, New South Wales'
        - 'Erina, New South Wales'
        - 'Ermington, New South Wales'
        - 'Eurunderee, New South Wales'
        - 'Evans Head, New South Wales'
        - 'Fairfield, Victoria'
        - 'Footscray, Victoria'
        - 'Frenchs Forest, New South Wales'
        - 'Goulburn, New South Wales'
        - 'Grafton, New South Wales'
        - 'Granville, New South Wales'
        - 'Guildford, New South Wales'
        - 'Guildford, New South Wales'
        - 'Gulgamree, New South Wales'
        - 'Gulgong, New South Wales'
        - 'Hamilton, New South Wales'
        - 'Hunters Hill, New South Wales'
        - 'Inverell, New South Wales'
        - 'Koolewong, New South Wales'
        - 'Lakemba, New South Wales'
        - 'Limekilns, New South Wales'
        - 'Limestone Flat, New South Wales'
        - 'Lindfield, New South Wales'
        - 'Lithgow, New South Wales'
        - 'Maryborough, Queensland'
        - 'McGraths Hill, New South Wales'
        - 'Menah, New South Wales'
        - 'Menindee, New South Wales'
        - 'Meroo, New South Wales'
        - 'Millthorpe, New South Wales'
        - 'Miranda, New South Wales'
        - 'Molong, New South Wales'
        - 'Mudgee, New South Wales'
        - 'Mullamuddy, New South Wales'
        - 'Muswellbrook, New South Wales'
        - 'Newport, New South Wales'
        - 'North Parramatta, New South Wales'
        - 'Northmead, New South Wales'
        - 'Northwood, New South Wales'
        - 'Northwood, New South Wales'
        - 'Orange, New South Wales'
        - 'Paddington, New South Wales'
        - 'Parramatta, New South Wales'
        - 'Putta Bucca, New South Wales'
        - 'Putta Bucca, New South Wales'
        - 'Queanbeyan, New South Wales'
        - 'Queen''s Pinch, New South Wales'
        - 'Quirindi, New South Wales'
        - 'Raymond Terrace, New South Wales'
        - 'Rooty Hill, New South Wales'
        - 'Roseville, New South Wales'
        - 'Rydalmere, New South Wales'
        - 'Rylstone, New South Wales'
        - 'Scone, New South Wales'
        - 'Seven Hills, New South Wales'
        - 'Sofala, New South Wales'
        - 'South West Rocks, New South Wales'
        - 'St Leonards, New South Wales'
        - 'St Marys, New South Wales'
        - 'Strathfield South, New South Wales'
        - 'Strathfield, New South Wales'
        - 'Tamworth, New South Wales'
        - 'Taree, New South Wales'
        - 'Teralba, New South Wales'
        - 'Thornleigh, New South Wales'
        - 'Turramurra, New South Wales'
        - 'Tweed Heads, New South Wales'
        - 'Urunga, New South Wales'
        - 'Wagga Wagga, New South Wales'
        - 'Wahroonga, New South Wales'
        - 'Wamberal, New South Wales'
        - 'Waratah, New South Wales'
        - 'Warilla, New South Wales'
        - 'Warrawong, New South Wales'
        - 'Wellington, New South Wales'
        - 'Werris Creek, New South Wales'
        - 'West Ryde, New South Wales'
        - 'Windeyer, New South Wales'
        - 'Windsor, New South Wales'
        - 'Wingham, New South Wales'
        - 'Wingham, New South Wales'
        - 'Winston Hills, New South Wales'
        - 'Wollongong, New South Wales'
        - 'Woollahra, New South Wales'
        - 'Woy Woy, New South Wales'
        - 'Wyong, New South Wales'
