parameters:
    locations:
        - 'Barraba, New South Wales'
        - 'Bathurst, New South Wales'
        - 'Bedgerabong, New South Wales'
        - 'Belmont, New South Wales'
        - 'Bocoble, New South Wales'
        - 'Bowraville, New South Wales'
        - 'Burwood, New South Wales'
        - 'Campsie, New South Wales'
        - 'Chatswood, New South Wales'
        - 'Cherrybrook, New South Wales'
        - 'Chester Hill, New South Wales'
        - 'Clandulla, New South Wales'
        - 'Coffs Harbour, New South Wales'
        - 'Cremorne, New South Wales'
        - 'Cudgegong, New South Wales'
        - 'Currumbin, Queensland'
        - 'Davistown, New South Wales'
        - 'Dural, New South Wales'
        - 'East Doncaster, Victoria'
        - 'Eastwood, New South Wales'
        - 'Echuca, Victoria'
        - 'Enfield, New South Wales'
        - 'Engadine, New South Wales'
        - 'Erina, New South Wales'
        - 'Ermington, New South Wales'
        - 'Eurunderee, New South Wales'
        - 'Evans Head, New South Wales'
        - 'Fairfield, Victoria'
        - 'Footscray, Victoria'
        - 'Frenchs Forest, New South Wales'
        - 'Goulburn, New South Wales'
        - 'Granville, New South Wales'
        - 'Guildford, New South Wales'
        - 'Gulgamree, New South Wales'
        - 'Gulgong, New South Wales'
        - 'Hunters Hill, New South Wales'
        - 'Inverell, New South Wales'
        - 'Limekilns, New South Wales'
        - 'Limestone Flat, New South Wales'
        - 'Lindfield, New South Wales'
        - 'Lithgow, New South Wales'
        - 'Menah, New South Wales'
        - 'Menindee, New South Wales'
        - 'Meroo, New South Wales'
        - 'Millthorpe, New South Wales'
        - 'Mudgee, New South Wales'
        - 'Mullamuddy, New South Wales'
        - 'Northmead, New South Wales'
        - 'Northwood, New South Wales'
        - 'Northwood, New South Wales'
        - 'Orange, New South Wales'
        - 'Parramatta, New South Wales'
        - 'Queen''s Pinch, New South Wales'
        - 'Rooty Hill, New South Wales'
        - 'Roseville, New South Wales'
        - 'Rydalmere, New South Wales'
        - 'Rylstone, New South Wales'
        - 'Seven Hills, New South Wales'
        - 'St Leonards, New South Wales'
        - 'Strathfield South, New South Wales'
        - 'Strathfield, New South Wales'
        - 'Taree, New South Wales'
        - 'Thornleigh, New South Wales'
        - 'Tweed Heads, New South Wales'
        - 'Wagga Wagga, New South Wales'
        - 'Wahroonga, New South Wales'
        - 'Wamberal, New South Wales'
        - 'Wellington, New South Wales'
        - 'West Ryde, New South Wales'
        - 'Windeyer, New South Wales'
        - 'Winston Hills, New South Wales'
        - 'Woollahra, New South Wales'
