parameters:
    profiles:
        - Rayner-39
        - Tarlinton-1
        - McAlary-16
        - McAlary-17
        - McAlary-19
        - Horrigan-2
        - McAlary-50
        - Welsh-315
        - Welsh-317
        - Hawke-82
        - McAlary-60
        - McAlary-62
        - McAlary-65
        - Hobbs-790
        - Welsh-321
        - Welsh-323
        - Welsh-325
        - Welsh-326
        - Welsh-327
        - Welsh-328
        - Welsh-329
        - Welsh-330
        - Harding-1034
        - Rayner-90
        - Stratton-246
        - Rayner-92
        - Rayner-94
        - Rayner-98
        - McAlary-131
        - Rayner-110
        - Welsh-336
        - Rayner-123
        - Rayner-124
        - McAlary-211
        - Hauber-11
        - Hauber-12
        - Hauber-13
        - Taylor-6896
        - Fraser-579
        - Voysey-5
        - Priddis-1
        - Rayner-200
        - Welsh-428
        - Broomfield-32
        - Broomfield-34
        - Laughlan-1
        - O'Donnell-410
        - McAlary-272
        - McAlary-277
        - Miller-15699
        - Miller-15700
        - Miller-15702
        - Miller-15703
        - Miller-15704
        - Boulton-111
        - Miller-15705
        - Darley-21
        - Gawthorne-4
        - Nott-99
        - Nott-101
        - Nott-115
        - McAlary-287
        - Rayner-453
        - Harvey-4348
        - Rayner-466
        - Rayner-510
        - Rayner-511
        - Rayner-513
        - Rayner-514
        - Rayner-536
        - Rayner-567
        - Brien-397
        - Marchant-572
        - Neist-11
        - Arnold-7059
        - Boulton-283
        - Edwards-13849
        - Webb-9778
        - Nixon-2387
        - Webb-9779
        - Nixon-2388
        - Nixon-2411
        - Nixon-2413
        - Nixon-2414
        - Nixon-2415
        - Nixon-2416
        - Nixon-2417
        - Nixon-2419
        - Webb-9850
        - Webb-9851
        - Webb-9852
        - Webb-9853
        - Webb-9854
        - Webb-9857
        - Marchant-824
        - Priddis-12
        - Corbett-1912
        - Nixon-2841
        - Formby-45
        - Broomfield-244
        - Broomfield-245
        - Rayner-838
        - Rayner-840
        - Rayner-841
        - Rayner-842
        - Rayner-843
        - Rayner-844
        - Rayner-850
        - Rayner-854
        - Swords-121
        - Arnold-9925
        - Arnold-9926
        - Arnold-9927
        - Last-369
        - Pincham-25
        - Sandry-85
        - Gawthorne-46
        - McAlary-302
        - Batty-478
        - Rayner-1139
        - Rayner-1141
        - Rayner-1145
        - Rhodes-6657
        - Rhodes-6658
        - Rhodes-6663
        - Rayner-1152
        - Bourke-855
        - Rayner-1154
        - Rayner-1159
        - Rayner-1162
        - Rayner-1165
        - Welsh-2633
        - Heath-6012
        - Heath-6157
        - Douglas-10807
        - Jonas-601
        - Jonas-603
        - Rayner-1347
        - McGrath-2888
        - Wright-40713
        - Swords-227
        - Wymer-266
        - Berghofer-68
        - Last-519
        - Rayner-1588
        - Rayner-1591
        - Atkins-5898
        - Stokes-5445
        - Rayner-1603
        - Rayner-1611
        - Perram-121
        - Calf-21
        - Rayner-1612
        - Rayner-1614
        - Thomas-44621
        - Rayner-1616
        - Lowe-11144
        - Rayner-1617
        - Harvey-14887
        - Rayner-1619
        - Rayner-1621
        - Rayner-1622
        - Rayner-1623
        - Jonas-679
        - Jonas-680
        - Jonas-681
        - Naughton-385
        - Naughton-389
        - Naughton-390
        - Naughton-391
        - Naughton-393
        - Naughton-394
        - Wood-36307
        - Rayner-1629
        - Rhodes-9016
        - Williams-92510
        - Brennan-3815
        - Brennan-3816
        - Rayner-2081
        - Rayner-2082
        - Frith-729
        - Graham-24028
        - Rayner-2089
        - Rayner-2091
        - Wheeler-21373
        - Fitzpatrick-3967
        - Rayner-2101
        - Rayner-2107
        - Chew-967
        - Patterson-19647
        - Sawyers-566
        - Copson-95
        - Bagnall-852
        - Hamilton-26383
        - Leahy-1120
        - Wilson-81820
        - Wilson-81821
        - Robertson-21184
        - Wilson-81822
        - Jonas-752
        - Thompson-65434
        - Thompson-65435
        - Brigden-154
        - Thompson-65437
        - Craven-2539
        - Thompson-65439
        - Thompson-65440
        - Thompson-65441
        - Thompson-65442
        - Crapp-341
        - Cook-37467
        - Cook-37469
        - Thompson-65450
        - Cameron-11991
        - Edwards-31162
        - Thompson-65451
        - Flynn-4713
        - Thompson-65453
        - Bradbery-11
        - Thompson-65462
        - Thompson-65463
        - Brigden-155
        - Thompson-65464
        - Thompson-65465
        - Thompson-65466
        - Cluff-512
        - Jonas-753
        - Wilkins-6239
        - Racher-252
        - Garling-145
        - Jonas-851
        - Jonas-852
        - Jonas-853
        - Rayner-2285
        - Sharp-12592
        - Clarke-19356
        - Rayner-2298
        - Walpole-574
        - Boyd-16567
        - McWhirter-706
        - Hill-47039
        - Judge-1264
        - Evans-37914
        - Rayner-2339
        - Wild-2698
        - Wild-2701
        - Wild-2706
        - Rayner-2341
        - Pauling-112
        - Rayner-2359
        - Rayner-2363
        - Gillespie-7171
        - Rayner-2373
        - Nixon-5180
        - Nixon-5181
        - Nixon-5182
        - Nixon-5183
        - Collins-31475
        - Nixon-5184
        - Nixon-5185
        - Offner-40
        - Nixon-5186
        - Jennings-11899
        - Nixon-5187
        - Nixon-5188
        - Lake-5259
        - Nixon-5189
        - Formby-133
        - Nixon-5190
        - Mills-22200
        - Nixon-5195
        - Nixon-5196
        - Pateman-278
        - Pateman-280
        - Pateman-281
        - Caughey-241
        - Pateman-282
        - Pateman-283
        - Pateman-284
        - Pateman-285
        - Miller-91086
        - Dray-509
        - Dray-510
        - Gilham-486
        - Dray-511
        - Dray-512
        - Dray-513
        - Dray-514
        - Gilham-487
        - Dray-515
        - Dray-516
        - Dray-517
        - Dray-518
        - O'Riel-63
        - Dray-519
        - Dray-520
        - Dray-521
        - Briggs-11149
        - Dray-522
        - Nott-1110
        - Downer-1075
        - Lee-37470
        - Lee-37471
        - Lee-37472
        - Nott-1112
        - Webb-22801
        - Smith-258432
        - Greenhalgh-1043
        - Webb-22802
        - Nixon-5198
        - Gentle-516
        - Nixon-5199
        - Button-2083
        - Nixon-5206
        - Potter-12815
        - Nixon-5208
        - Cafe-44
        - Nixon-5209
        - Willis-12749
        - Nixon-5218
        - Harkham-2
        - Miller-91109
        - Berry-20139
        - Miller-91110
        - Garrett-11290
        - Miller-91111
        - Fox-20099
        - Miller-91112
        - Cross-11408
        - Miller-91113
        - Hill-47111
        - Smith-258464
        - Smith-258465
        - Nesbitt-2522
        - Nesbitt-2523
        - Williams-105513
        - Williams-105514
        - Nesbitt-2524
        - Simmons-17063
        - Boulton-1074
        - McDonald-24400
        - Noonan-1460
        - Simpson-21590
        - Nesbitt-2528
        - Porter-21856
        - Broadfoot-424
        - Smith-258517
        - Smith-258518
        - Cross-11417
        - Smith-258519
        - Cole-26198
        - Smith-258520
        - Coffey-4730
        - Smith-258521
        - Law-5235
        - Smith-258522
        - Carney-3185
        - Smith-258523
        - Smith-258525
        - Smith-258526
        - Hughes-25626
        - Law-5236
        - Law-5237
        - Monaghan-1004
        - Gillis-2367
        - Rayner-2379
        - Rayner-2380
        - Hunt-23729
        - Hunt-23730
        - Hunt-23731
        - Hunt-23732
        - Hunt-23733
        - Hunt-23734
        - Hunt-23735
        - Hunt-23736
        - Hunt-23737
        - Hunt-23738
        - Rayner-2381
        - Reynolds-23717
        - Rayner-2382
        - Rayner-2383
        - Rayner-2384
        - Rayner-2385
        - Rayner-2386
        - Rayner-2387
        - Rayner-2389
        - Rayner-2390
        - Rayner-2391
        - Bowles-3889
        - Rayner-2392
        - Rayner-2393
        - McGee-5736
        - McGee-5737
        - Walsh-10556
        - Walsh-10566
        - Rayner-2395
        - Cunningham-15247
        - Rayner-2396
        - Rayner-2397
        - Rayner-2398
        - Rayner-2399
        - Smith-258676
        - Rayner-2403
        - Maher-3238
        - Rayner-2404
        - Bennett-33009
        - Bennett-33010
        - Agnew-2036
        - Thomas-54222
        - Bennett-33011
        - Rayner-2405
        - Laughlan-13
        - Laughlan-14
        - Casimir-32
        - Casimir-33
        - Casimir-34
        - Smith-258684
        - Casimir-35
        - Rogers-36508
        - Casimir-36
        - Norton-10071
        - Casimir-37
        - Robinson-48390
        - Casimir-38
        - Laughlan-15
        - Dunshea-133
        - Laughlin-2355
        - Laughlin-2356
        - Laughlin-2357
        - Laughlan-16
        - Laughlan-17
        - Laughlan-18
        - Laughlan-20
        - Rayner-2406
        - Priddis-25
        - Priddis-26
        - McMahon-4401
        - Priddis-27
        - Fitzsimmons-1051
        - Priddis-28
        - Priddis-29
        - White-68810
        - Priddis-30
        - Priddis-31
        - Priddis-32
        - Priddis-46
        - Priddis-47
        - Coventry-726
        - Priddis-48
        - Marchant-1847
        - Priddis-97
        - Webb-22824
        - Priddis-98
        - Smedley-1298
        - Priddis-99
        - Young-48605
        - Young-48606
        - McCarthy-6767
        - Priddis-100
        - Kelly-24675
        - Priddis-101
        - Priddis-102
        - Altmann-387
        - Priddis-103
        - Harvey-18086
        - Rayner-2408
        - Ritchie-5158
        - Rayner-2409
        - McCaul-136
        - Rayner-2410
        - Rayner-2411
        - Rayner-2412
        - McFarlane-2879
        - Rayner-2415
        - Rayner-2416
        - Rayner-2417
        - Rayner-2420
        - Noonan-1468
        - Rayner-2422
        - Watson-32465
        - Rayner-2425
        - Rayner-2426
        - Ridout-617
        - Rayner-2427
        - Rayner-2428
        - Meagher-720
        - Rayner-2440
        - McGrath-3854
        - McGrath-3857
        - Rayner-2447
        - Davis-91577
        - Rayner-2465
        - Mills-22239
        - Rayner-2466
        - Fitzgerald-8900
        - Fitzgerald-8902
        - Rayner-2468
        - Bell-34945
        - Rayner-2470
        - Howard-27091
        - Rayner-2471
        - Rayner-2492
        - Nipperess-52
        - Rayner-2501
        - Cottee-128
        - Rayner-2505
        - Rayner-2506
        - Mara-228
        - Rayner-2508
        - Roberts-44080
        - McGrath-3895
        - McGrath-3896
        - Williams-105766
        - Archinal-27
        - Harvey-18099
        - Cameron-13202
        - Harvey-18101
        - Harvey-18102
        - Harvey-18103
        - Rayner-2525
        - Grayston-22
        - Grayston-23
        - Rayner-2526
        - Rayner-2527
        - Ryan-15817
        - Rayner-2532
        - Condon-1346
        - Rayner-2533
        - Field-7159
        - Rayner-2534
        - Welsh-4187
        - Rayner-2535
        - Boyling-11
        - Rayner-2536
        - Wright-51933
        - Rayner-2537
        - Hazell-455
        - Rayner-2538
        - Brown-132819
        - Rayner-2539
        - Kearns-1530
        - Rayner-2544
        - Marshall-23244
        - Rayner-2545
        - Robbins-9398
        - Rayner-2547
        - Muller-12312
        - Rayner-2560
        - Rayner-2561
        - Weir-4864
        - Marsh-11058
        - Marsh-11061
        - Cosier-60
        - Marsh-11069
        - Marsh-11079
        - Willis-12799
        - Marsh-11080
        - Curtis-16425
        - Rayner-2564
        - Grimshaw-632
        - Reid-17908
        - Harding-8644
        - Woolley-2497
        - Dew-1347
        - Pitt-2495
        - Pitt-2502
        - Gawthorne-88
        - Seymour-5429
        - Gawthorne-90
        - Gawthorne-91
        - Smede-24
        - Gawthorne-94
        - Fox-20195
        - Gawthorne-95
        - Halpin-708
        - Gawthorne-100
        - Adams-55710
        - Gawthorne-101
        - Wade-11919
        - Gawthorne-102
        - Scott-47099
        - Rayner-2570
        - Walker-54485
        - Rayner-2579
        - Rayner-2580
        - Rayner-2583
        - Rayner-2584
        - Rayner-2586
        - Rhodes-10322
        - Rayner-2592
        - Sheppard-4915
        - Rayner-2598
        - Grant-18966
        - Rayner-2602
        - Grant-18968
        - Mortimer-2200
        - Cox-35663
        - Cox-35668
        - Cox-35670
        - Cox-35673
        - Neal-7434
        - Wilkins-6605
        - Rayner-2610
        - Nott-1116
        - Jonas-873
        - Davidson-15736
        - McGowan-3432
        - Rayner-2614
        - Rayner-2616
        - Rayner-2619
        - Harding-8736
        - Cullum-633
        - Priddis-105
        - Taylor-83087
        - Phipps-3163
        - Phipps-3164
        - McGowan-3451
        - Patterson-21433
        - Patterson-21437
        - Patterson-21438
        - Patterson-21440
        - Patterson-21441
        - Moxon-295
        - Doherty-3764
        - Rhodes-10448
        - Fitzsimmons-1109
        - Fitzsimmons-1110
        - Graham-26384
        - Rayner-2716
        - Rayner-2727
        - Rayner-2728
        - Sharpe-4290
        - Rayner-2743
        - Rayner-2744
        - Rayner-2748
        - Irwin-5793
        - Rayner-2756
        - Rayner-2769
        - Rayner-2772
        - Gould-8290
        - Rayner-2779
        - Rayner-2798
        - Rayner-2806
        - Welch-11550
        - Cohen-5987
        - Hardy-9696
        - Booth-10556
        - Perkins-18739
        - Milgate-208
        - Sims-9125
        - Clarke-20379
        - Cochran-6372
        - Brown-139187
        - Brown-139189
        - Brown-139190
        - Arlow-80
        - Lahene-3
        - Morris-34708
        - Yarnton-15
        - Boyd-17416
        - Boyd-17422
        - Jonas-888
        - Marchant-1918
        - Marchant-1919
        - Jonas-889
        - Garling-151
        - Garling-152
        - Garling-153
        - Garling-154
        - Campbell-51480
        - Cox-37105
        - Taylor-86227
        - Richards-18913
        - Sarah-932
        - Norbery-4
        - Norbery-5
        - Miller-95752
        - Miller-95753
        - Miller-95754
        - Miller-95755
        - Miller-95756
        - Miller-95757
        - Norbery-6
        - McKee-6351
        - Norbery-7
        - Norbery-8
        - Norbery-9
        - Norbery-10
        - Norbery-11
        - Norbery-12
        - Norbery-13
        - Meredith-5538
        - Nixon-5439
        - Nixon-5440
        - Nixon-5441
        - Nixon-5442
        - Nixon-5443
        - Nixon-5444
        - Welsh-4363
        - Welsh-4364
        - Welsh-4365
        - Welsh-4366
        - Welsh-4367
        - Welsh-4368
        - Drane-653
        - Drane-654
        - Drane-655
        - Drane-656
        - Poulter-550
        - Brittain-1761
        - Veron-46
        - Laurence-1017
        - Hunt-24969
        - Hunt-24970
        - Hunt-24971
        - Hunt-24972
        - McKinnon-3611
        - Hunt-24982
        - Hunt-24983
        - Hunt-24984
        - Meredith-5549
        - Hunt-24997
        - Hunt-24998
        - Hunt-24999
        - Jamieson-3966
        - Hibberd-406
        - Coppard-293
        - Coppard-294
        - Coppard-295
        - Coppard-296
        - Coppard-297
        - Coppard-298
        - Coppard-299
        - Coppard-300
        - Coppard-301
        - Coppard-302
        - Coppard-303
        - Chaffer-23
        - Laughlan-23
        - Laughlan-24
        - Laughlan-25
        - Laughlan-26
        - Laughlan-27
        - Laughlan-28
        - Peterson-16183
        - Laughlan-29
        - Laughlan-30
        - Laughlin-2469
        - Laughlin-2470
        - Laughlin-2471
        - Spencer-25066
        - O'Malley-1233
        - Laughlin-2472
        - Laughlin-2473
        - Swords-267
        - Swords-268
        - Luke-2080
        - Luke-2081
        - Luke-2082
        - Luke-2083
        - Luke-2084
        - Luke-2085
        - Luke-2086
        - Millstead-36
        - Coventry-774
        - Coventry-775
        - 