monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.error.log"
            level: error
            channels: ["!event","!wikitree"]
        request:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.request.log"
            level: debug
            channels: ["request"]
        php:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.php.log"
            level: debug
            channels: ["php"]
        wikitree:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.wikitree.log"
            level: debug
            channels: ["wikitree"]
        doctrine:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.doctrine.log"
            level: info
            max_files: 10
            channels: ["doctrine"]
        main_debug:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.debug.log"
            level: debug
            channels: ["!event","!wikitree","!doctrine"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        #console:
        #    type: console
        #    process_psr_3_messages: false
        #    channels: ["!event", "!doctrine", "!console"]
    channels: ['wikitree']