tags:
    HEAD:
        name: Header
        description: Information about the entire GEDCOM file.
        subrecords:
            - GEDC:
                name: GEDCOM
                description: Information about the use of GEDCOM in a GEDCOM File.
                subrecords:
                    - VERS:
                        name: Version
                        description: Indicates which version of a product, item, or publication is being used or referenced.
            - CHAR:
                name: CHARACTER
                description: An indicator of the character set used in writing this automated information.
            - LANG:
                name: LANGUAGE
                description: The name of the language used in a communication or transmission of information.